### ISSUE TITLE
[BUG] Arrays are casted as string or record

### ISSUE THREAD

**Issue by awoehrl** [datacoves/dbt-coves#339]
**Describe the bug**
When using `dbt-coves generate sources`, the resulting SQL file doesn't consider arrays. These are casted as string. 
Also dbt-coves doesn't traverse through the array when generating the source.yml file. Only the top level will be represented as column.
This is at least true for BigQuery.

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a source table with arrays on BigQuery.
2. Run command `dbt-coves generate sources`

**Expected behaviour**
The SQL should contain all fields and wrap them in structs and arrays correctly.
The yml should show all levels of columns.

Best
Andreas

**Comment by SHREYASH96OG** [comment]
**calloc** just allocates a big swath of memory - not an array of pointers to other arrays.

fgets expects a pointer to the memory location it should dump it's stuff at.

So instead of giving it the contents of **data[i]**, you want to give it the address of **data[i]** so it can put its stuff there.

**fgets(&data[i], 70, fsol);**

You'll probably also need to adjust your loop so that it goes up by 70-odd characters at a time rather than one.

hope it will work
shreyas

**Comment by noel** [comment]
@awoehrl can you try with the latest version so we can close this?

**Comment by volderette** [comment]
Thank you very much! Just tried again with my data and I can confirm it is working now!

**Comment by awoehrl** [comment]
Thank you very much! Just tried again with my data and I can confirm it is working now!
